# This file loads the generated data of meiotic and mitotic rates and plots them
# using different visualization methods.

# To start with, load all the packages right below.

# All figures for the paper are under each specific section titles. The other
# sections contain code for relevant graphs mainly for self-assurance. The distribution
# (Wilcoxon) and correlation tests are included under "Statistics".

## Relevant data info in the inst/data/ folder ##

# Currently in use:
# 08-20, 21, 22_1-10 -- misdiagnosed rates for dispersal = 0, 0.5, and 1

# 08-17c, d, e -- 3000 ABC_seq Lenormand data for Capalbo

# 08-16c, d, e -- 3000 ABC_seq Lenormand data for Viotti

# 08-09, 08-09b, 08-10 -- Capalbo data, 1,000 combinations (0.01 tolerance) at 0, 0.5,
# and 1 dispersal, 3,000 total.

# 08-08, 08-08b -- Capalbo data, 10,000 combinations (0.1 tolerance) at 0, 0.5,
# and 1 dispersal, 30,000 total.

# 08-06, 08-07, 08-07b -- 10,000 combinations (0.1 tolerance) at 0, 0.5, and 1 dispersal, 30,000 total.

# 08-02, 08-04, 08-05 -- 256 cells, 1,000 combinations (0.01 tolerance) each (3,000 total),
# 100,000 proportions of aneuploidy each (300,000 total). 0, 0.5, 1 dispersal.

# 07-30 -- 200 cells, 100 combinations each (0.01 tolerance), 10,000 proportions
# each. 0 dispersal. Small sample check

# 07-20, 07-25, 07-26 -- 200 cells, 1,000 combinations each (3,000 total), 100,000
# proportions of aneuploidy each (300,000 total). 0, 0.5, 1 dispersal

# dispersal_ranges.csv -- all 3,000 combinations of error rates, excluding proportions
# of aneuploidy. Generated by combining 08-02, 08-04, 08-05

# dispersal_full.csv -- all 3,000 combinations and 300,000 proportions. Generated
# by combining 08-02, 08-04, 08-05

# dispersal_ranges_0.1_tol -- all 30,000 combinations (0.1 tolerance), excluding
# proportions. Generated by combining 08-06, 08-07, 08-07b

# dispersal_ranges_full_0.1_tol -- all 30,000 combinations (0.1 tolerance) and 3,000,000
# proportions. Generated by combining 08-06, 08-07, 08-07b

if (!require(ggplot2))
  install.packages("ggplot2", repos = "http://cran.us.r-project.org")
library(ggplot2)
if (!require(readr))
  install.packages("readr", repos = "http://cran.us.r-project.org")
library(readr)
if (!require(gridExtra))
  install.packages("gridExtra", repos = "http://cran.us.r-project.org")
library(gridExtra)
if (!require(ggcorrplot))
  install.packages("ggcorrplot", repos = "http://cran.us.r-project.org")
library(ggcorrplot)
if (!require(tidyr))
  install.packages("tidyr", repos = "http://cran.us.r-project.org")
library(tidyr)
if (!require(viridis))
  install.packages("viridis", repos = "http://cran.us.r-project.org")
library(viridis)
if (!require(dplyr))
  install.packages("dplyr", repos = "http://cran.us.r-project.org")
library(dplyr)
if (!require(ggpubr))
  install.packages("ggpubr", repos = "http://cran.us.r-project.org")
library(ggpubr)
if (!require("RColorBrewer")) {
  install.packages("RColorBrewer")
  library(RColorBrewer)
}
if (!require("gt")) {
  install.packages("gt")
  library(gt)
}
if (!require("vtable")) {
  install.packages("vtable")
  library(vtable)
}
if (!require("kableExtra")) {
  install.packages("kableExtra")
  library(kableExtra)
}
if (!require(bayestestR)) {
  install.packages("bayestestR")
}
library(bayestestR)
if (!require(reshape2)) {
  install.packages("reshape2")
}
library(reshape2)
if (!require(patchwork)) {
  install.packages("patchwork")
}
library(patchwork)
# -------------Load and Process Data-------------------------
# Locate the folder to investigate
date <- "2024-08-06"

# Set column names
my_data_cols <-
  read_table(paste0("inst/data/", date, "/1.txt"),
             n_max  = 1,
             col_names = FALSE)
my_data_cols <- cbind('embryo', my_data_cols)

# Read the first txt file
my_data <-
  read_table(paste0("inst/data/", date, "/1.txt"),
             skip = 1,
             col_names = FALSE)
colnames(my_data) <- my_data_cols[1, ]

# Read all the rest of the data
for (i in 2:100) {
  temp <-
    read_table(paste0("inst/data/", date, "/", i, ".txt"),
               skip = 1,
               col_names = FALSE)
  colnames(temp) <- my_data_cols[1, ]
  my_data <- rbind(my_data, temp)
}

# Combine two tables
# Locate the folder to investigate
date <- "2024-08-07b"

# Set column names
new_data_cols <-
  read_table(paste0("inst/data/", date, "/1.txt"),
             n_max  = 1,
             col_names = FALSE)
new_data_cols <- cbind('embryo', new_data_cols)

# Read the first txt file
new_data <-
  read_table(paste0("inst/data/", date, "/1.txt"),
             skip = 1,
             col_names = FALSE)
colnames(new_data) <- new_data_cols[1, ]

# Read all the rest of the data
for (i in 2:100) {
  temp <-
    read_table(paste0("inst/data/", date, "/", i, ".txt"),
               skip = 1,
               col_names = FALSE)
  colnames(temp) <- new_data_cols[1, ]
  new_data <- rbind(new_data, temp)
}

my_data <- rbind(new_data, my_data)



# -------------Graphing-------------------------
theme_set(theme_bw())

#### Draw Histograms ####
h <-
  ggplot(data = my_data, aes(x = my_data$prob.meio))  +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold")
  )
h <- h + geom_histogram(
  binwidth = 0.1,
  color = "#000000",
  fill = "lightblue"
) + labs(x = "Probability of Meiotic Error", y = "Number of Embryos") +
  geom_vline(
    aes(xintercept = mean(my_data$prob.meio)),
    color = "red",
    linewidth = 1.25,
    linetype = "dashed"
  ) +
  scale_y_continuous(expand = c(0, 0)) + theme_classic()

# Mitotic
hm <-
  ggplot(data = my_data, aes(x = my_data$prob.mito))  +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold")
  )
hm <- hm + geom_histogram(
  binwidth = 0.025,
  color = "#000000",
  fill = "lightblue",
) + labs(x = "Probability of Mitotic Error", y = "Number of Embryos") +
  geom_vline(
    aes(xintercept = mean(my_data$prob.mito)),
    color = "red",
    linewidth = 1.25,
    linetype = "dashed"
  ) +
  scale_y_continuous(expand = c(0, 0)) + theme_classic()

# Prop.aneu
ha <-
  ggplot(data = my_data, aes(x = my_data$prop.aneu))  +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold")
  )
ha <- ha + geom_histogram(
  binwidth = 0.05,
  color = "#000000",
  fill = "lightblue",
) + labs(x = "Proprotion of Aneuploidy", y = "Number of Embryos") +
  geom_vline(
    aes(xintercept = mean(my_data$prop.aneu)),
    color = "red",
    linewidth = 1.25,
    linetype = "dashed"
  ) +
  scale_y_continuous(expand = c(0, 0)) + theme_classic()



#### Distribution of Dispersal ####
p <- ggplot(data = my_data, aes(x =  my_data$dispersal, )) + labs(x = "Probability of Mitotic Error", y = "Dispersal", color = "Dispersal")
p <- p + geom_histogram(
  binwidth = 0.15,
  color = "#000000",
  fill = "lightblue",
) + labs(x = "Dispersal", y = "Number of Embryos") +
  geom_vline(
    aes(xintercept = mean(my_data$dispersal)),
    color = "red",
    linewidth = 1.25,
    linetype = "dashed"
  ) +
  scale_y_continuous(expand = c(0, 0)) + theme_classic()



# Arrange the panel
grid.arrange(h, hm, ha, p)


#### Draw scatterplots ####

g <-
  ggplot(data = my_data, aes(x = prob.meio, y = prob.mito))
g <- g + geom_point(color = "steelblue") + labs(x = "Probability of Meiotic Error", y = "Probability of Mitotic Error") +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold")
  ) +
  theme_classic()

# Scatterplots with dispersal
d <- ggplot(data = my_data, aes(x = prob.meio, y = prob.mito, color = dispersal))

d <- d + geom_point() + labs(x = "Probability of Meiotic Error", y = "Probability of Mitotic Error", color = "Dispersal") +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold"),
    legend.position = c(.87, .8),
    legend.background = element_rect(fill = "transparent"),
    panel.grid = element_blank()
  ) +
  guides(color = guide_colorsteps())  + scale_color_viridis_c() +   geom_rug()

# Arrange panel
grid.arrange(d, g)


# Scatter plot with Euclidean distances
my_data <- my_data %>% mutate(euclidean = sqrt((euploid - 0.388) ^ 2 + (mosaic - 0.188) ^ 2 +
                                                 (aneuploid - 0.426) ^ 2))
ggplot(data = my_data,
       aes(
         x = prob.meio,
         y = prob.mito,
         color = euclidean,
         shape = factor(dispersal)
       )) + geom_point(size = 1) +
  labs(
    x = "Probability of Meiotic Error",
    y = "Probability of Mitotic Error",
    color = "Distance",
    shape = "Dispersal"
  ) +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold"),
    legend.position = c(.87, .8),
    legend.background = element_rect(fill = "transparent"),
    panel.grid = element_blank()
  ) +
  guides(color = guide_colorsteps())  + scale_color_viridis_c() + geom_rug() +
  theme_bw()


#### Statistics ####

### Correlation ###
print(cor(my_data$prob.meio, my_data$prob.mito))

corm = cor(my_data[, c('prob.meio', 'prob.mito', 'dispersal')])
print(corm)

pmat = cor_pmat(my_data[, c('prob.meio', 'prob.mito', 'dispersal')])
print(pmat)

ggcorrplot(
  corm,
  type = "lower",
  lab = TRUE,
  p.mat = pmat,
  insig = "blank"
)

cor.test(disp_0$prob.meio, disp_0$prob.mito)

print(cor(disp_0.5$prob.meio, disp_0.5$prob.mito))

print(cor(disp_1$prob.meio, disp_1$prob.mito))


### Correct Biopsy ###
# sum(my_data$mosaic)*100/500000
# 0.218514
# sum(my_data$euploid)*100/500000
# 0.336616
# sum(my_data$aneuploid)*100/500000
# 0.44487
# 168308 euploid, 109257 mosaic, 222435 aneuploid (should all be mosaic)


#------For Paper-----------------------------------------------------

#### Figure 2 #############################################################

data1 <- read.csv("inst/data/2024-08-16c/data.csv")
data2 <- read.csv("inst/data/2024-08-16d/data.csv")
data3 <- read.csv("inst/data/2024-08-16e/data.csv")
dispersal_ranges <- rbind(data1, data2, data3)

# Together
library(reshape2)
data_melt <- melt(
  dispersal_ranges,
  id.vars = c("dispersal", "euploid", "mosaic", "aneuploid"),
  measure.vars = c("prob.meio", "prob.mito")
)

variable_labels <- c(prob.meio = "Probability of Meiotic Error", prob.mito = "Probability of Mitotic Error")


max_estimates <- data_melt %>%
  group_by(dispersal, variable) %>%
  summarise(map_estimate(value)[2])


# Plot the histograms
ggplot(data_melt, aes(x = value)) +
  facet_grid(
    dispersal ~ variable,
    scales = "free_x",
    axes = "all",
    axis.labels = "all_y",
    labeller = labeller(variable = variable_labels)
  ) +
  geom_histogram(
    data = subset(data_melt, variable == "prob.meio"),
    binwidth = 0.005,
    boundary = 0,
    fill = "steelblue",
    color = "black"
  ) +
  geom_histogram(
    data = subset(data_melt, variable == "prob.mito"),
    binwidth = 0.001,
    boundary = 0,
    fill = "steelblue",
    color = "black"
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    sec.axis = sec_axis(
      ~ . ,
      name = "Dispersal",
      breaks = NULL,
      labels = NULL
    )
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Error Rates", y = "Number of Embryos") +
  geom_vline(
    data = max_estimates,
    aes(xintercept = MAP_Estimate),
    color = "red",
    linewidth = 0.75,
    linetype = "dashed"
  ) +
  theme_bw()


# Boxplot arrangement
theme_set(theme_bw())
p1 <- ggplot(dispersal_ranges, aes(y = dispersal_ranges$prob.meio)) +
  geom_boxplot() +
  facet_wrap(~ dispersal) + labs(y = "Probability of Meiotic Error") +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  )
# one box per variety
p2 <- ggplot(dispersal_ranges, aes(y = dispersal_ranges$prob.mito)) +
  geom_boxplot() +
  facet_wrap(~ dispersal) + labs(y = "Probability of Mitotic Error", x =
                                   "Dispersal") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())

grid.arrange(p1, p2)


#### Figure 3 ##################################################

# Read prop.aneu data to create dispersal_ranges
data1 <- read.csv("inst/data/2024-08-16c/full_data.csv")
data2 <- read.csv("inst/data/2024-08-16d/full_data.csv")
data3 <- read.csv("inst/data/2024-08-16e/full_data.csv")
dispersal_ranges <- rbind(data1, data2, data3)

# By cell (bar at 0% represents the number of euploid embryos only)
euploid_heights <- dispersal_ranges %>%
  group_by(dispersal) %>%
  summarise(euploid_height = (sum(prop.aneu == 0) / n()))

total_count <- sum(dispersal_ranges$dispersal == 0)

prop.hist <- ggplot(dispersal_ranges, aes(x = prop.aneu)) +
  facet_grid(rows = vars(factor(dispersal, levels = c("0", "0.5", "1"))), scales = "fixed") +
  geom_histogram(
    data = dispersal_ranges,
    aes(y = ..count.. / total_count),
    binwidth = 1 / 257,
    boundary = 0,
    fill = "red",
    color = "black"
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(
    expand = c(0, 0),
    sec.axis = sec_axis(
      ~ . ,
      name = "Dispersal",
      breaks = NULL,
      labels = NULL
    ),
    labels = scales::percent_format()
  ) +
  labs(x = "Proportion of Aneuploidy", y = "Percentage of Embryos", tag = "A") +
  theme_bw() +
  geom_segment(
    data = euploid_heights,
    aes(
      x = 0.1,
      xend = 0,
      y = euploid_height + 0.25,
      yend = euploid_height
    ),
    arrow = arrow(length = unit(0.3, 'cm')),
    size = 0.5,
    color = "red"
  ) +
  geom_text(
    data = euploid_heights,
    aes(
      x = 0.1,
      y = euploid_height + 0.25,
      label = sprintf("%.1f%%", euploid_height * 100)
    ),
    vjust = -0.5,
    hjust = -0.1,
    fontface = 'bold',
    size = 4.5,
    show.legend = FALSE
  )


###### ggplot barplot

biopsy_data <- dispersal_ranges %>%
  mutate(
    category = case_when(
      prop.aneu == 0 ~ "Euploid",
      prop.aneu > 0 & prop.aneu < 1 ~ "Mosaic Aneuploid",
      prop.aneu == 1 ~ "Fully Aneuploid"
    )
  )

embryo_types <- biopsy_data %>%
  group_by(dispersal, prob.meio, prob.mito, category) %>%
  summarise(count = n()) %>%
  mutate(label_ypos = cumsum(count) + 0.5) %>%
  mutate(percent = count / sum(count) * 100)

embryo_types$category <- factor(embryo_types$category,
                                levels = c("Euploid", "Mosaic Aneuploid", "Fully Aneuploid"))

# calculate mean and standard deviations
embryo_sum <- embryo_types %>%
  group_by(dispersal, category) %>%
  summarize(mean = mean(percent), std = sd(percent)) %>%
  mutate(xpos = c(12, 40, 80)) %>%
  mutate(new_mean = cumsum(mean))

# percentages
# Horizontal percentage bar chart
percent.bar <- ggplot(embryo_sum, aes(
  x = factor(dispersal, levels = c(1, 0.5, 0)),
  y = mean,
  fill = factor(
    category,
    levels = c("Fully Aneuploid", "Mosaic Aneuploid", "Euploid")
  )
)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = new_mean - std, ymax = new_mean + std),
                width = 0.2,
                color = "red") +
  labs(x = "Dispersal Level",
       y = "Percentage of Embryos",
       fill = "Embryo Type",
       tag = "B") +
  geom_label(
    aes(y = xpos, label = sprintf("%.1f%%", mean)),
    color = "red",
    fill = "white",
    fontface = "bold",
    size = 4
  ) +
  scale_fill_viridis(discrete = TRUE) +
  scale_y_continuous(expand = c(0, 0)) +
  theme_classic() + coord_flip()

prop.hist + percent.bar

#### Table 1 #########################################################

data1 <- read.csv("inst/data/2024-08-16c/data.csv")
data2 <- read.csv("inst/data/2024-08-16d/data.csv")
data3 <- read.csv("inst/data/2024-08-16e/data.csv")
dispersal_ranges <- rbind(data1, data2, data3)

disp_0 <- subset(dispersal_ranges, dispersal == 0)
disp_0.5 <- subset(dispersal_ranges, dispersal == 0.5)
disp_1 <- subset(dispersal_ranges, dispersal == 1)

stats_0 <- st(disp_0[, c('prob.meio', 'prob.mito')], out = "return")
stats_0 <- t(stats_0)
stats_0.5 <- st(disp_0.5[, c('prob.meio', 'prob.mito')], out = "return")
stats_0.5 <- t(stats_0.5)
stats_1 <- st(disp_1[, c('prob.meio', 'prob.mito')], out = "return")
stats_1 <- t(stats_1)
stats_sum <- (cbind(stats_0, stats_0.5, stats_1))

# Add MAP and remove redundant rows
stats_sum <- stats_sum[!(row.names(stats_sum) %in% c("N", "Std. Dev.", "Min", "Max")), ]

data_melt <- melt(
  dispersal_ranges,
  id.vars = c("dispersal", "euploid", "mosaic", "aneuploid"),
  measure.vars = c("prob.meio", "prob.mito")
)

variable_labels <- c(prob.meio = "Probability of Meiotic Error", prob.mito = "Probability of Mitotic Error")

max_estimates <- data_melt %>%
  group_by(dispersal, variable) %>%
  summarise(map_estimate(value)[2])

stats_sum <- rbind(
  c("Dispersal 0", "", "Dispersal 0.5", "", "Dispersal 1", ""),
  stats_sum,
  MAP = signif(max_estimates$MAP_Estimate, 2)
)

kbl(stats_sum, format = "markdown")



stats_0 <- st(disp_0[, c('euploid', 'mosaic', 'aneuploid')], out = "return")
stats_0 <- t(stats_0)
stats_0.5 <- st(disp_0.5[, c('euploid', 'mosaic', 'aneuploid')], out = "return")
stats_0.5 <- t(stats_0.5)
stats_1 <- st(disp_1[, c('euploid', 'mosaic', 'aneuploid')], out = "return")
stats_1 <- t(stats_1)
stats_sum <- (cbind(stats_0, stats_0.5, stats_1))
stats_sum <- rbind(c("Dispersal 0", "", "", "Dispersal 0.5", "", "", "Dispersal 1", "", ""),
                   stats_sum)
kbl(stats_sum, format = "markdown")

#### Figure 4 ###################################
# import dispersal_ranges
data1 <- read.csv("inst/data/2024-08-16c/data.csv")
data2 <- read.csv("inst/data/2024-08-16d/data.csv")
data3 <- read.csv("inst/data/2024-08-16e/data.csv")
dispersal_ranges <- rbind(data1, data2, data3)


# Together in the same panel
ggscatter(
  dispersal_ranges,
  x = "prob.meio",
  y = "prob.mito",
  add = "reg.line",
  conf.int = TRUE,
  cor.coeff.args = list(label.x.npc = "left", label.y.npc = "bottom"),
  cor.coef = TRUE,
  cor.method = "pearson",
  xlab = "Probability of Meiotic Error",
  ylab = "Probability of Mitotic Error"
) + facet_grid(dispersal ~ .,
               scales = "free",
               axes = "all",
               axis.labels = "all_y") +
  scale_y_continuous(sec.axis = sec_axis(
    ~ . ,
    name = "Dispersal",
    breaks = NULL,
    labels = NULL
  ))

# Euclidean distance in the same plot
dispersal_ranges <- dispersal_ranges %>% mutate(euclidean = sqrt((euploid - 0.388) ^ 2 + (mosaic - 0.188) ^ 2 +
                                                                   (aneuploid - 0.426) ^ 2))
ggplot(data = dispersal_ranges, aes(x = prob.meio, y = prob.mito, color = euclidean)) +
  geom_point(size = 1) + facet_grid(dispersal ~ .,
                                    scales = "fixed",
                                    axes = "all",
                                    axis.labels = "all_y") +
  labs(
    x = "Probability of Meiotic Error",
    y = "Probability of Mitotic Error",
    color = "Distance",
    shape = "Dispersal"
  ) +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold"),
    legend.position = c(.87, .8),
    legend.background = element_rect(fill = "transparent"),
    panel.grid = element_blank()
  ) + scale_y_continuous(sec.axis = sec_axis(
    ~ . ,
    name = "Dispersal",
    breaks = NULL,
    labels = NULL
  )) +
  guides(color = guide_colorsteps())  + scale_color_viridis_c(oob = scales::squish) + geom_rug() +
  theme_bw()

# Plotting with weights
dispersal_ranges <- dispersal_ranges %>% mutate(euclidean = sqrt((euploid - 0.388) ^ 2 + (mosaic - 0.188) ^ 2 +
                                                                   (aneuploid - 0.426) ^ 2))
ggplot(data = dispersal_ranges, aes(x = prob.meio, y = prob.mito, size = weights, color = euclidean)) +
  geom_point() + facet_grid(dispersal ~ .,
                                    scales = "fixed",
                                    axes = "all",
                                    axis.labels = "all_y") +
  labs(
    x = "Probability of Meiotic Error",
    y = "Probability of Mitotic Error",
    size = "Weights",
    color = "Distance",
    shape = "Dispersal"
  ) +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold"),
    legend.position = c(.87, .8),
    legend.background = element_rect(fill = "transparent"),
    panel.grid = element_blank()
  ) + scale_y_continuous(sec.axis = sec_axis(
    ~ . ,
    name = "Dispersal",
    breaks = NULL,
    labels = NULL
  )) +
  guides(color = guide_colorsteps())  + scale_color_viridis_c(oob = scales::squish) + geom_rug() +
  theme_bw() + scale_size_area(max_size = 2)

# Histogram with weights
library(reshape2)
data_melt <- melt(
  dispersal_ranges,
  id.vars = c("dispersal", "euploid", "mosaic", "aneuploid"),
  measure.vars = c("prob.meio", "prob.mito")
)

variable_labels <- c(prob.meio = "Probability of Meiotic Error", prob.mito = "Probability of Mitotic Error")


max_estimates <- data_melt %>%
  group_by(dispersal, variable) %>%
  summarise(map_estimate(value)[2])


# Plot the histograms
ggplot(data_melt, aes(x = value)) +
  facet_grid(
    dispersal ~ variable,
    scales = "free_x",
    axes = "all",
    axis.labels = "all_y",
    labeller = labeller(variable = variable_labels)
  ) +
  geom_histogram(
    data = subset(data_melt, variable == "prob.meio"),
    aes(weight = weights),
    binwidth = 0.005,
    boundary = 0,
    fill = "steelblue",
    color = "black"
  ) +
  geom_histogram(
    data = subset(data_melt, variable == "prob.mito"),
    aes(weight = weights),
    binwidth = 0.001,
    boundary = 0,
    fill = "steelblue",
    color = "black"
  ) +
  scale_y_continuous(
    expand = c(0, 0),
    sec.axis = sec_axis(
      ~ . ,
      name = "Dispersal",
      breaks = NULL,
      labels = NULL
    )
  ) +
  scale_x_continuous(expand = c(0, 0)) +
  labs(x = "Error Rates", y = "Number of Embryos") +
  geom_vline(
    data = max_estimates,
    aes(xintercept = MAP_Estimate),
    color = "red",
    linewidth = 0.75,
    linetype = "dashed"
  ) +
  theme_bw()


#### Misdiagnosed Rates ##############
date <- "2024-08-22b"
data <- c()
for(i in 1:10) {
  new_data <- read.csv(paste0("inst/data/", date, "/data_" , i, ".csv"))
  data <- rbind(data, new_data)
}

data$Mosaic.Aneuploid <- data$Mosaic.Aneuploid / 1000
mosaic_data <- data %>%  group_by(misclassification) %>%
  summarise(proportion =mean(Mosaic.Aneuploid), stdev = sd(Mosaic.Aneuploid))

ggplot(data = mosaic_data, aes(x = misclassification, y = proportion)) +
  geom_point(size = 3) +
  # facet_grid(dispersal ~ .,
  #                                   scales = "free",
  #                                   axes = "all",
  #                                   axis.labels = "all_y") +
  labs(x = "Biopsy Misclassification Rate", y = "Proportion of Mosaic Aneuploidy Embryos", ) +
  theme(
    axis.title.x = element_text(vjust = 0, size = 10, face = "bold"),
    axis.title.y = element_text(vjust = 2, size = 10, face = "bold"),
    legend.position = c(.87, .8),
    legend.background = element_rect(fill = "transparent"),
    panel.grid = element_blank()
  ) +
 geom_errorbar(aes(ymin=proportion-stdev, ymax=proportion+stdev), width=.1) + 
  theme_bw()
